"""hints table

Revision ID: 424e9e0e37e3
Revises: 345bdd3bbc07
Create Date: 2020-08-30 13:23:21.339639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424e9e0e37e3'
down_revision = '345bdd3bbc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hint')
    # ### end Alembic commands ###
